# Use the official OpenJDK base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/orderservice.jar /app/orderservice.jar

# Expose port 8080 (adjust if your application uses a different port)
EXPOSE 8080

# Specify the command to run on container startup
CMD ["java", "-jar", "orderservice.jar"]
