# Use the official OpenJDK base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/inventory-service.jar /app/inventory-service.jar

# Expose port 8080
EXPOSE 8080

# Specify the command to run on container startup
CMD ["java", "-jar", "inventory-service.jar"]
